name: P4A Android APK Build with Pandas

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses-dev \
              cmake libffi-dev libssl-dev build-essential automake gettext
          pip install --upgrade pip
          pip install cython "setuptools<60.0"

      - name: Install python-for-android
        run: |
          pip install "python-for-android==2024.01.21"

      - name: Build with python-for-android
        run: |
          # 【【【 核心修正：分步编译 】】】
          p4a apk --name "A股异动监控" \
                  --package "org.test.stockmonitor" \
                  --version 0.1 \
                  --bootstrap sdl2 \
                  # 关键：我们编译一个包含 kivy 和 pandas (以及其依赖 numpy) 的基础版本
                  --requirements="python3,kivy,pandas" \
                  # 关键：我们把纯 Python 的库放到一个特殊参数里，让它们在之后被添加
                  --private . \
                  --permission INTERNET \
                  --arch arm64-v8a \
                  --release \
                  --symlink-bootstrap-files \
                  --copy-libs \
                  --activity-class-name="org.kivy.android.PythonActivity" \
                  --service="p4aservice:src/p4aservice.py" \
                  --python-service-argument="--requirements=akshare,requests,lxml,charset-normalizer,idna,openssl,pyopenssl" \
                  --window
                  
      - name: Find and rename APK
        run: |
          find . -type f -name "*-release-unsigned.apk" -exec mv {} A-Stock-Monitor.apk \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: A-Stock-Monitor.apk
