name: P4A Android APK Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git \
              zip \
              unzip \
              autoconf \
              libtool \
              pkg-config \
              zlib1g-dev \
              libncurses-dev \
              cmake \
              libffi-dev \
              libssl-dev \
              build-essential \
              automake \
              gettext
          pip install --upgrade pip
          pip install cython "setuptools<60.0"

      - name: Install python-for-android
        run: |
          pip install python-for-android

      - name: Build with python-for-android
        run: |
          # 【【【 核心修正 】】】
          # 使用 --bootstrap=webview 可大大减少依赖编译问题，--window 让其全屏
          p4a apk --name "A股异动监控" \
                  --package "org.test.stockmonitor" \
                  --version 0.1 \
                  --bootstrap webview \
                  --requirements "python3,kivy,pandas,akshare,requests,lxml,charset-normalizer,idna,openssl,pyopenssl" \
                  --arch arm64-v8a \
                  --release \
                  --permission INTERNET \
                  --private . \
                  --window
        
      - name: Find and rename APK
        run: |
          # 查找生成的release APK并重命名
          find . -type f -name "*-release-unsigned.apk" -exec mv {} A-Stock-Monitor.apk \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: A-Stock-Monitor.apk
