name: Build APK with Manual Toolchain Downgrade

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Dockerized Manual Setup
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            ubuntu:20.04 \
            /bin/bash -c " \
              set -ex; \
              export DEBIAN_FRONTEND=noninteractive; \
              sed -i 's@//archive.ubuntu.com@//mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list; \
              apt-get update; \
              # 安装除 autoconf/libtool 之外的所有依赖
              apt-get install -y --no-install-recommends \
                build-essential git zip unzip patch openjdk-17-jdk python3-pip python3-venv \
                pkg-config cmake gettext zlib1g-dev libncurses5-dev libffi-dev libssl-dev wget; \
              
              # 【【【 核心修正：手动安装旧版的 autoconf 和 libtool 】】】
              # 安装 m4, 它是 autoconf 的依赖
              apt-get install -y m4; \
              # 下载、编译和安装 autoconf 2.69
              wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz; \
              tar xzf autoconf-2.69.tar.gz; \
              cd autoconf-2.69; \
              ./configure --prefix=/usr; \
              make; \
              make install; \
              cd ..; \
              # 下载、编译和安装 libtool 2.4.6
              wget http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz; \
              tar xzf libtool-2.4.6.tar.gz; \
              cd libtool-2.4.6; \
              ./configure --prefix=/usr; \
              make; \
              make install; \
              cd ..; \
              
              # 现在，在一个拥有了正确版本工具链的环境中，继续我们的流程
              python3 -m venv venv; \
              . venv/bin/activate; \
              pip install --upgrade pip; \
              pip install 'buildozer==1.5.0' cython 'setuptools<60.0'; \
              cd /workdir; \
              yes | buildozer -v android debug; \
            "
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: bin/*.apk
