name: Build APK (Lightweight)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Dockerized Stable Environment
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            ubuntu:20.04 \
            /bin/bash -c " \
              set -ex; \
              export DEBIAN_FRONTEND=noninteractive; \
              sed -i 's@//archive.ubuntu.com@//mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list; \
              apt-get update; \
              # 安装一个精简但完整的依赖列表
              apt-get install -y --no-install-recommends \
                build-essential make git zip unzip patch openjdk-17-jdk python3-pip python3-venv \
                pkg-config cmake gettext autoconf automake libtool libtool-bin \
                zlib1g-dev libncurses5-dev libffi-dev libssl-dev; \
              python3 -m venv venv; \
              . venv/bin/activate; \
              pip install --upgrade pip; \
              pip install 'buildozer==1.5.0' cython 'setuptools<60.0'; \
              cd /workdir; \
              yes | buildozer -v android debug; \
            "
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: bin/*.apk
