name: Build APK with Official GitHub Container Registry Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with the Official Kivy GHCR image
        run: |
          # 运行 Kivy 官方的、托管在 GitHub 上的 Buildozer 镜像
          # 这个拉取过程将在 GitHub 内部网络进行，速度快且不会失败
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            ghcr.io/kivy/buildozer:latest \
            /bin/bash -c " \
              set -ex; \
              # 镜像内部已经包含了所有工具，我们直接编译即可
              # 我们甚至可能不需要 apt-get，但为了保险起见，先加上
              apt-get update && apt-get install -y --no-install-recommends libffi-dev || echo 'apt failed but continuing'; \
              cd /workdir; \
              buildozer -v android debug; \
            "
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: bin/*.apk
