name: Buildozer Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 关键第一步：设置正确的 JDK 17 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 【【【 新增的、最关键的前置步骤 】】】
      # 准备 Android SDK 环境，下载命令行工具
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.0.1
      
      # 关键第二步：现在，我们可以安全地使用 sdkmanager 来安装 NDK 了
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653" --sdk_root=${ANDROID_HOME}

      # 关键第三步：安装系统依赖和 Buildozer
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool autoconf unzip patch
          pip install --upgrade pip
          pip install "buildozer==1.5.0" cython "setuptools<60.0"

      # 关键第四步：直接运行 Buildozer 编译
      - name: Build with Buildozer
        run: buildozer -v android debug

      # 关键第五步：上传产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: bin/*.apk
