name: Build APK with Official Kivy Android Packager

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with the Official Kivy Android Packager Docker image
        run: |
          # 运行 Kivy 官方的、预设好一切的 Docker 镜像来完成编译
          # 这次使用了绝对正确的镜像名称
          docker run --rm \
              -v ${{ github.workspace }}:/app \
              kivy/kivy-android-packager:latest \
              /bin/bash -c "cd /app && buildozer -v android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: bin/*.apk
