name: Build APK with Official Kivy-CI Docker Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Kivy-CI Docker image
        run: |
          # 运行 Kivy 官方的、预设好一切的 Docker 镜像来完成编译
          # 它内部包含了版本匹配的工具链和所有依赖的补丁
          docker run --rm \
              -v ${{ github.workspace }}:/app \
              kivy/kivy-ci:android \
              /bin/bash -c "cd /app && buildozer -v android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stockmonitor-apk
          path: bin/*.apk
